In [1]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
iris = load_iris()

In [6]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
from sklearn.model_selection import StratifiedKFold

In [4]:
kf = StratifiedKFold(n_splits=10)

In [5]:
from sklearn.model_selection import cross_val_score

In [7]:
cross_val_score(LogisticRegression(),iris.data,iris.target)

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [12]:
cross_val_score(LogisticRegression(),iris.data,iris.target).mean()

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9733333333333334

In [14]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [13]:
cross_val_score(SVC(),iris.data,iris.target).mean()

0.9666666666666666

In [9]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [15]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target).mean()

0.9666666666666668

In [10]:
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [16]:
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target).mean()

0.9666666666666668